
from PySide6.QtCore import (
    Qt,
)

from PySide6.QtWidgets import (
    QAbstractItemView,
    QHeaderView,
    QMessageBox,
    QPushButton,
    QTableView,
    QVBoxLayout,
    QHBoxLayout,
    QLabel,
    QWidget,
)

from modelrailroadops.services.car_move_service import (
    CarMoveService,
)

from modelrailroadops.ui.operations.car_move_table_model import (
    CarMoveTableModel,
)

from modelrailroadops.ui.styles import (
    TABLE_SELECTION_STYLE,
)


class CarMovesWidget(QWidget):
    """
    Widget used to display and manage CarMove records
    for a selected Operations Session.

    Provides functionality to:

        - Display car movements
        - Refresh car movements
        - Delete a selected car movement

    Car moves are normally generated by the operations
    generation process rather than entered manually.
    """

    def __init__(
        self,
        parent=None,
    ):

        super().__init__(
            parent
        )

        self.operations_session_id = None

        #
        # Main layout.
        #

        layout = QVBoxLayout(
            self
        )

        #
        # Selected session label.
        #

        self.session_label = QLabel(
            "No Operations Session selected."
        )

        layout.addWidget(
            self.session_label
        )

        #
        # Buttons.
        #

        button_layout = QHBoxLayout()

        self.delete_button = QPushButton(
            "Delete Move"
        )

        self.refresh_button = QPushButton(
            "Refresh"
        )

        button_layout.addWidget(
            self.delete_button
        )

        button_layout.addWidget(
            self.refresh_button
        )

        button_layout.addStretch()

        layout.addLayout(
            button_layout
        )

        #
        # Table model.
        #

        self.model = (
            CarMoveTableModel()
        )

        #
        # Table.
        #

        self.table = QTableView()

        self.table.setStyleSheet(
            TABLE_SELECTION_STYLE
        )

        self.table.setModel(
            self.model
        )

        self.table.setSelectionBehavior(
            QAbstractItemView.SelectRows
        )

        self.table.setSelectionMode(
            QAbstractItemView.SingleSelection
        )

        self.table.setAlternatingRowColors(
            True
        )

        self.table.setEditTriggers(
            QAbstractItemView.NoEditTriggers
        )

        self.table.setSortingEnabled(
            False
        )

        self.table.horizontalHeader().setSectionResizeMode(
            QHeaderView.ResizeToContents
        )

        self.table.horizontalHeader().setStretchLastSection(
            True
        )

        self.table.verticalHeader().setVisible(
            False
        )

        layout.addWidget(
            self.table
        )

        #
        # Signals.
        #

        self.delete_button.clicked.connect(
            self.delete_move
        )

        self.refresh_button.clicked.connect(
            self.refresh
        )

        self.table.selectionModel().selectionChanged.connect(
            self.selection_changed
        )

        #
        # Initial state.
        #

        self.update_button_states()

    #
    # Set Operations Session.
    #

    def set_operations_session(
        self,
        operations_session,
    ):

        if operations_session is None:

            self.operations_session_id = None

            self.session_label.setText(
                "No Operations Session selected."
            )

            self.model.set_moves(
                []
            )

            self.update_button_states()

            return

        self.operations_session_id = (
            operations_session.id
        )

        name = (
            getattr(
                operations_session,
                "name",
                None,
            )
            or ""
        )

        if name:

            self.session_label.setText(
                (
                    "Operations Session: "
                    f"{name}"
                )
            )

        else:

            self.session_label.setText(
                (
                    "Operations Session: "
                    f"{self.operations_session_id}"
                )
            )

        self.refresh()

    #
    # Set Operations Session ID.
    #

    def set_operations_session_id(
        self,
        operations_session_id,
        session_name=None,
    ):

        self.operations_session_id = (
            operations_session_id
        )

        if operations_session_id is None:

            self.session_label.setText(
                "No Operations Session selected."
            )

            self.model.set_moves(
                []
            )

        else:

            if session_name:

                self.session_label.setText(
                    (
                        "Operations Session: "
                        f"{session_name}"
                    )
                )

            else:

                self.session_label.setText(
                    (
                        "Operations Session: "
                        f"{operations_session_id}"
                    )
                )

            self.refresh()

        self.update_button_states()

    #
    # Refresh.
    #

    def refresh(
        self,
    ):

        selected_move_id = (
            self.get_selected_move_id()
        )

        if self.operations_session_id is None:

            self.model.set_moves(
                []
            )

            self.update_button_states()

            return

        moves = (
            CarMoveService.get_by_operations_session(
                self.operations_session_id
            )
        )

        self.model.set_moves(
            moves
        )

        self.table.resizeColumnsToContents()

        #
        # Restore previous selection.
        #

        if selected_move_id is not None:

            for row, move in enumerate(
                self.model.moves
            ):

                if move.id == selected_move_id:

                    self.table.selectRow(
                        row
                    )

                    break

        self.update_button_states()

    #
    # Get selected move.
    #

    def get_selected_move(
        self,
    ):

        indexes = (
            self.table.selectionModel()
            .selectedRows()
        )

        if not indexes:

            QMessageBox.information(
                self,
                "Car Move",
                "Please select a car move.",
            )

            return None

        return self.model.get_move(
            indexes[0].row()
        )

    #
    # Get selected move without message.
    #

    def get_selected_move_without_message(
        self,
    ):

        indexes = (
            self.table.selectionModel()
            .selectedRows()
        )

        if not indexes:

            return None

        return self.model.get_move(
            indexes[0].row()
        )

    #
    # Get selected move ID.
    #

    def get_selected_move_id(
        self,
    ):

        move = (
            self.get_selected_move_without_message()
        )

        if move is None:

            return None

        return move.id

    #
    # Selection changed.
    #

    def selection_changed(
        self,
        selected,
        deselected,
    ):

        self.update_button_states()

    #
    # Update button states.
    #

    def update_button_states(
        self,
    ):

        move = (
            self.get_selected_move_without_message()
        )

        has_move = (
            move is not None
        )

        self.delete_button.setEnabled(
            has_move
        )

        self.refresh_button.setEnabled(
            self.operations_session_id is not None
        )

    #
    # Delete move.
    #

    def delete_move(
        self,
    ):

        move = (
            self.get_selected_move()
        )

        if move is None:

            return

        train_display = (
            self.model.get_train_display(
                move
            )
        )

        car_display = (
            self.model.get_car_display(
                move
            )
        )

        move_type = (
            move.move_type
            or ""
        )

        answer = QMessageBox.question(
            self,
            "Delete Car Move",
            (
                "Delete this car movement?\n\n"
                f"Train: {train_display}\n"
                f"Car: {car_display}\n"
                f"Move: {move_type}\n\n"
                "This cannot be undone."
            ),
            (
                QMessageBox.Yes
                | QMessageBox.No
            ),
            QMessageBox.No,
        )

        if answer != QMessageBox.Yes:

            return

        success, result = (
            CarMoveService.delete(
                move.id
            )
        )

        if not success:

            QMessageBox.warning(
                self,
                "Delete Car Move",
                str(
                    result
                ),
            )

            return

        self.refresh()
